sudo: false

language: android

android:
  components:

    # All the build system components should be at the latest version
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-23

    # The libraries we can't get from Maven Central or similar
    - extra

script:
  - ./gradlew clean assemble test -Dpre-dex=false --stacktrace # run tests

cache:
  directories:
    - $HOME/.gradle

