language: android

android:
  components:

    # All the build system components should be at the latest version
    - tools
    - platform-tools
    - build-tools-21.1.2
    - android-20

    # The libraries we can't get from Maven Central or similar
    - extra-android-support
    - extra-android-m2repository

script:
  - ./gradlew clean test  # run tests
